name: Build Phosphor, run the integration test suite

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '16' ]
    steps:
      - uses: actions/checkout@v3
      - name: Build Phosphor
        run: mvn -B -ntp -DskipTests install
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run tests
        run: mvn install -ntp -Pdacapo
  deploy:
    runs-on: self-hosted
    needs: build-and-test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KEY_PASSPHRASE: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
        run: bash ./deployment/deploy.sh
